#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:springcoredb
#spring.datasource.username=sa
#spring.datasource.password=

#spring.h2.console.enabled=true
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.url=jdbc:h2:./myselectdb;AUTO_SERVER=TRUE
#spring.datasource.username=sa
#spring.datasource.password=
#
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.generate-ddl=true
#logging.level.org.hibernate.SQL=debug
#logging.level.org.hibernate.type.descriptor.sql=trace

#server.port=8091

spring:
  # DB ??
  datasource:
    # ??? H2 DB? ?? URL
    url: jdbc:h2:mem:springcoredb
    # ??? ?? ????
    driver-class-name: org.h2.Driver
    # springboot 2.4 ??? username? ? ??????. ??? ??? ?????.
    username: sa
  jpa:
    # JPA? ???? SQL? ? ? ??.
    show-sql: true
    # ??? ?? ???? ??? ?? ??. ?? - create, ??? - none
    # ????? ??? create? ????
    # ???? none ?? ???. create?? ??? ???? ?? ??????.
    hibernate:
      ddl-auto: create
  # ?? ?? ? ?? always
  output:
    ansi:
      enabled: always
# ???? ??? ?? trace
logging:
  level:
    org.hibernate.type: trace